#!/bin/bash
APP_NAME="audiobookshelf"
APP_DIR="${TRIM_APPDEST}"
APP_DATA_DIR="${TRIM_PKGVAR}"

LOG_FILE="${TRIM_PKGVAR}/${TRIM_APPNAME}.log"
PID_FILE="${TRIM_PKGVAR}/${TRIM_APPNAME}.pid"

SERVICE_COMMAND="$APP_DIR/bin/audiobookshelf-launch"
SVC_BACKGROUND=y
SVC_WRITE_PID=y

export NODE_ENV="production"
export AUDIOBOOKSHELF_PORT="13378"
