#!/bin/bash
APP_NAME=embyserver
APP_DIR="${TRIM_APPDEST}"
APP_DATA_DIR="${TRIM_PKGVAR}"

LOG_FILE="${TRIM_PKGVAR}/${TRIM_APPNAME}.log"
PID_FILE="${TRIM_PKGVAR}/${TRIM_APPNAME}.pid"

### Package specific variables and functions
### ----------------------------------------

SERVICE_COMMAND="$APP_DIR/bin/emby-server $APP_DATA_DIR"
SVC_BACKGROUND=y
SVC_WRITE_PID=y

