#!/bin/bash
### Generic variables and functions
### -------------------------------


# start-stop-status script redirect stdout/stderr to LOG_FILE
LOG_FILE="${TRIM_PKGVAR}/${TRIM_APPNAME}.log"

# Service command has to deliver its pid into PID_FILE
PID_FILE="${TRIM_PKGVAR}/${TRIM_APPNAME}.pid"

APP_NAME=embyserver
APP_DIR="${TRIM_APPDEST}"
PID_FILE="${TRIM_PKGVAR}/${APP_NAME}.pid"
APP_DATA_DIR="${TRIM_PKGVAR}"

### Package specific variables and functions
### ----------------------------------------

SERVICE_COMMAND="$APP_DIR/bin/emby-server $APP_DATA_DIR"
SVC_BACKGROUND=y
SVC_WRITE_PID=y

