#!/bin/bash
# Audiobookshelf Server Control Script

APP_NAME="audiobookshelf"
APP_DIR="${TRIM_APPDEST}"
APP_DATA_DIR="${TRIM_PKGVAR}"

LOG_FILE="${TRIM_PKGVAR}/${TRIM_APPNAME}.log"
PID_FILE="${TRIM_PKGVAR}/${TRIM_APPNAME}.pid"

### Package specific variables and functions
### ----------------------------------------

SERVICE_COMMAND="$APP_DIR/bin/audiobookshelf"
SVC_BACKGROUND=y
SVC_WRITE_PID=y

# 环境变量
export NODE_ENV="production"
export AUDIOBOOKSHELF_CONFIG_DIR="/config"
export AUDIOBOOKSHELF_DATA_DIR="/data"
export AUDIOBOOKSHELF_METADATA_PATH="/metadata"
export AUDIOBOOKSHELF_CACHE_PATH="/cache"
export AUDIOBOOKSHELF_PORT="13378"

# 服务启动前的准备
svc_pre_start() {
    # 确保目录存在
    mkdir -p "/config" "/data" "/metadata" "/cache"
    mkdir -p "/data/audiobooks" "/data/podcasts"
    mkdir -p "/cache/images" "/cache/audio"
    
    return 0
}